### PR TITLE
Jw branch2

### PR DESCRIPTION
**Pull request by Josh-Webb**
Get All "Order Product" with Test.

### CODE REVIEW

**Comment by hcleland** [comment]
GET all test passed with flying colors! 👍

**Review by keishacard — APPROVED** [review]
I LOVE ORDERING FORM AMAZON ITS THE BEST SO FAST

**Review by hcleland — APPROVED** [review]
GET all test passed with only single plain jane color. 👍

**Review by ImHughes — APPROVED** [review]
🍻👍👍Here is a beer and 2 thumbs up good job Josh!

**Pull request merged**
